# gcp_provision_vms.yml
---
- name: Provision GCP VMs for the assessment
  hosts: localhost
  connection: local
  tasks:
    - name: Create VM for Apache (gcp-webserver)
      google.cloud.gcp_compute_instance:
        name: gcp-webserver
        zone: us-central1-a # CHANGE THIS TO YOUR DESIRED ZONE
        machine_type: e2-medium # e2-micro is free tier, but limited
        image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
        network_interfaces:
          - network: default
            access_configs:
              - name: External NAT # Assigns a public IP
                nat_ip_in_use_external_ip_address: "{{ lookup('env', 'EXTERNAL_IP_WEBSERVER') }}" # Optional: use existing external IP
        tags:
          - webserver
          - ssh
        metadata:
          ssh-keys: ubuntu:{{ lookup('file', '~/.ssh/id_rsa.pub') }} # Adds your public key for 'ubuntu' user
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 15
              disk_type: pd-standard
        state: present
      register: webserver_vm_details

    - name: Create VM for RabbitMQ (gcp-messaging)
      google.cloud.gcp_compute_instance:
        name: gcp-messaging
        zone: us-central1-a # CHANGE THIS TO YOUR DESIRED ZONE
        machine_type: e2-medium
        image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
        network_interfaces:
          - network: default
            access_configs:
              - name: External NAT
                nat_ip_in_use_external_ip_address: "{{ lookup('env', 'EXTERNAL_IP_MESSAGING') }}"
        tags:
          - rabbitmq
          - ssh
        metadata:
          ssh-keys: ubuntu:{{ lookup('file', '~/.ssh/id_rsa.pub') }}
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 15
              disk_type: pd-standard
        state: present
      register: messaging_vm_details

    - name: Create VM for PostgreSQL (gcp-database)
      google.cloud.gcp_compute_instance:
        name: gcp-database
        zone: us-central1-a # CHANGE THIS TO YOUR DESIRED ZONE
        machine_type: e2-medium
        image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
        network_interfaces:
          - network: default
            access_configs:
              - name: External NAT
                nat_ip_in_use_external_ip_address: "{{ lookup('env', 'EXTERNAL_IP_DATABASE') }}"
        tags:
          - postgresql
          - ssh
        metadata:
          ssh-keys: ubuntu:{{ lookup('file', '~/.ssh/id_rsa.pub') }}
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 20
              disk_type: pd-standard
        state: present
      register: database_vm_details

    - name: Create VM for Elasticsearch (gcp-search-node)
      google.cloud.gcp_compute_instance:
        name: gcp-search-node
        zone: us-central1-a # CHANGE THIS TO YOUR DESIRED ZONE
        machine_type: e2-standard-4 # Elasticsearch requires more resources
        image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
        network_interfaces:
          - network: default
            access_configs:
              - name: External NAT
                nat_ip_in_use_external_ip_address: "{{ lookup('env', 'EXTERNAL_IP_SEARCH_NODE') }}"
        tags:
          - elasticsearch
          - ssh
        metadata:
          ssh-keys: ubuntu:{{ lookup('file', '~/.ssh/id_rsa.pub') }}
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              disk_size_gb: 50
              disk_type: pd-standard
        state: present
      register: search_node_vm_details

    - name: Print VM IPs
      ansible.builtin.debug:
        msg: |
          Webserver IP: {{ webserver_vm_details.instance.networkInterfaces[0].accessConfigs[0].natIP }}
          Messaging IP: {{ messaging_vm_details.instance.networkInterfaces[0].accessConfigs[0].natIP }}
          Database IP: {{ database_vm_details.instance.networkInterfaces[0].accessConfigs[0].natIP }}
          Search Node IP: {{ search_node_vm_details.instance.networkInterfaces[0].accessConfigs[0].natIP }}

